### ISSUE TITLE
internationalization self review result for IMSC-HRM

### ISSUE THREAD

**Issue by himorin** [w3c/imsc-hrm#18]
Short i18n review checklist is [here](http://w3c.github.io/i18n-activity/reviews/shortchecklist)

1. [ ] _If the spec (or its implementation) contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc),_

    Does not apply.
    
2. [ ] _If the spec (or its implementation) allows content authors to produce typographically appealing text, either in its own right, or in association with graphics._

    The purpose of the IMSC-HRM specification is to allow subtitle and caption authors and providers to verify that the content they provide does not exceed defined complexity levels, so that playback systems can render the content synchronised with the author-specified display times. In order to define complexity levels, the [specification](https://w3c.github.io/imsc-hrm/spec/imsc-hrm.html#paint-text) makes assumptions on the rendering complexity of various scripts.

3. [ ] _If the spec (or its implementation) allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc._

    Does not apply.

4. [ ] _If the spec (or its implementation) allows searching or matching of text, including syntax and identifiers_

    Does not apply.

5. [ ] _If the spec (or its implementation) sorts text_

    Does not apply.

6. [ ] _If the spec (or its implementation) captures user input_

    Does not apply.

7. [ ] _If the spec (or its implementation) deals with time in any way that will be read by humans and/or crosses time zone boundaries_

    Does not apply. The spec does deal with times, as specified via the IMSC and TTML specifications, but no presentation of times is dealt with within the IMSC-HRM specification itself.

8. [ ] _If the spec (or its implementation) allows any character encoding other than UTF-8._

    Does not apply.

9. [ ] _If the spec (or its implementation) defines markup._

    Does not apply.

10. [ ] _If the spec (or its implementation) deals with names, addresses, time & date formats, etc_

    Does not apply.

11. [ ] _If the spec (or its implementation) describes a format or data that is likely to need localization._

    Does not apply. The IMSC and TTML specifications define a format that is suitable for use in the activity of localization, but no specific requirements relating to localization exist within the IMSC-HRM specification.

12. [ ] _If the spec (or its implementation) makes any reference to or relies on any cultural norms_

    Does not apply.

**Comment by palemieux** [comment]
@himorin What is the requested action on this issue?

**Comment by himorin** [comment]
@palemieux WG is requesting horizontal reviews based on these results of self checklists, so close each once each HR finished.

**Comment by nigelmegitt** [comment]
@himorin How do we conclude this now that we have done the self review checklist. I see that the tracking issue https://github.com/w3c/i18n-activity/issues/1439 is open, but I'm not sure what that means for us.

**Comment by himorin** [comment]
ah, there is still no official procedure to handle companion tracker to HR request (I suppose).
I've commented to propose closing i18n review request as completed, and this and tracker should be closed in parallel to that.

**Comment by himorin** [comment]
closing this : all HR needs-resolution closed.
